// src/components/Navbar.vue
<template>
  <b-navbar toggleable="lg" type="dark" variant="dark">
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-brand to="/">
        <img
          class="ow-logo img-fluid"
          src="assets/imgs/navbar/v-logo-red.png"
        />
        <span class="title-text">Valorant Agent Picker</span>
      </b-navbar-brand>
      <!-- Right aligned nav items -->
      <b-navbar-nav class="ml-auto">
        <b-nav-item to="/about">About</b-nav-item>
        <b-nav-item
          href="https://github.com/andrerfcsantos/valorant-agent-picker"
          target="_blank"
        >
          Github
        </b-nav-item>
        <b-nav-item href="https://discord.gg/2yb3ZPzjve" target="_blank">
          <img class="bmc-logo img-fluid" src="assets/imgs/discord.png" />
        </b-nav-item>
        <b-nav-item
          href="https://www.buymeacoffee.com/heropickers"
          target="_blank"
        >
          <img class="bmc-logo img-fluid" src="assets/imgs/navbar/bmc.svg" />
        </b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script>
export default {
  name: "Navbar",
};
</script>

<style scoped>
a,
a:active,
a:focus,
a:hover {
  text-decoration: none !important;
  color: white;
}

b-navbar {
  color: white;
  min-height: 5vh;
}

.navbar-brand {
  display: flex;
}

.navbar-brand span {
  align-self: flex-end;
}

a,
ul,
div,
span {
  align-items: center;
}

.title-text {
  font-size: 1.5rem;
  text-decoration: none;
  font-family: Valorant-Regular, Arial, Helvetica, sans-serif;
}

img {
  max-height: 2em;
}

.ow-logo {
  padding-right: 0.5em;
}
</style>

// src/components/Navbar.tsx
"use client";

import { useState } from "react";
import Link from "next/link";

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav className="flex flex-wrap items-center justify-between bg-[#111111] px-4 py-2 min-h-[5vh] font-[family-name:var(--font-inter)]">
      <button
        className="lg:hidden text-white text-2xl border border-gray-500 rounded px-2 py-1"
        onClick={() => setIsOpen(!isOpen)}
        aria-label="Toggle navigation"
      >
        ☰
      </button>

      <div
        className={`${isOpen ? "flex" : "hidden"} lg:flex flex-col lg:flex-row w-full lg:w-auto items-center lg:justify-between flex-1`}
      >
        <Link href="/" className="flex items-end no-underline text-white">
          <img
            className="h-[2em] pr-2"
            src="/imgs/navbar/v-logo-red.png"
            alt="Valorant logo"
          />
          <span
            className="text-2xl no-underline"
            style={{ fontFamily: "Valorant-Regular, Arial, Helvetica, sans-serif" }}
          >
            Valorant Agent Picker
          </span>
        </Link>

        <div className="flex flex-col lg:flex-row items-center gap-2 lg:gap-4 mt-2 lg:mt-0">
          <Link
            href="/about"
            className="text-white no-underline hover:text-gray-300"
          >
            About
          </Link>
          <a
            href="https://github.com/andrerfcsantos/valorant-agent-picker"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white no-underline hover:text-gray-300"
          >
            Github
          </a>
          <a
            href="https://discord.gg/2yb3ZPzjve"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              className="h-[2em]"
              src="/imgs/discord.png"
              alt="Discord"
            />
          </a>
          <a
            href="https://www.buymeacoffee.com/heropickers"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              className="h-[2em]"
              src="/imgs/navbar/bmc.svg"
              alt="Buy Me A Coffee"
            />
          </a>
        </div>
      </div>
    </nav>
  );
}
